# PRACTICA CON LIBRERÍA PANDAS

**Ejercicio SF Salaries**   

Utilizaremos el `SF Salaries Dataset` Kaggle. Simplemente sigue y completa las tareas que se detallan a continuación en negrita. Las tareas serán cada vez más difíciles a medida que avance.

La idea principal es aplicar pandas para organizar informacion, manipularla, buscar información en el dataset

**Importar pandas como pd. y visualizar la version que se esta usando**

In [1]:
import numpy as np
import pandas as pd

**Cargar el archivo "Salaries.csv" en un dataframe denominado "salarios"**

In [6]:
salarios=pd.read_csv('/home/andrescg/Documentos/IA/CEIABD_26_27/PIA_26_27/NOTEBOOKS DEL AULA/datasets/Salaries.csv',index_col=0)
display(salarios)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
Id,,,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

**Usar el método `.info()` para saber cuantas Columnas de atributos hay y que tipo de datos tiene cada una.**

In [9]:
salarios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148654 entries, 1 to 148654
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   EmployeeName      148654 non-null  object
 1   JobTitle          148654 non-null  object
 2   BasePay           148045 non-null  float64
 3   OvertimePay       148650 non-null  float64
 4   OtherPay          148650 non-null  float64
 5   Benefits          112491 non-null  float64
 6   TotalPay          148654 non-null  float64
 7   TotalPayBenefits  148654 non-null  float64
 8   Year              148654 non-null  int64
 9   Notes             0 non-null       float64
 10  Agency            148654 non-null  object
 11  Status            0 non-null       float64
dtypes: float64(8), int64(1), object(3)
memory usage: 18.8+ MB

- Segun la información del dataframe su tamaño es de *memory usage: 14.7+ MB*

- las columnas **Notes** y **Status** solamente tienen valores *NaN*. Verificar que dice **0 non-null**, es decir, 0 valores son diferentes a *NaN* y, por tanto, todos los valores son *NaN* en esas columnas

**Eliminar las columnas *Notes* y *Status*. Se debe usar el parámetro para realizarlo de forma permanente (inplace), y luego se debe visualizar el número de filas y columnas tiene despues de eliminar las columnas**

In [10]:
del salarios['Notes']
del salarios['Status']
salarios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148654 entries, 1 to 148654
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   EmployeeName      148654 non-null  object
 1   JobTitle          148654 non-null  object
 2   BasePay           148045 non-null  float64
 3   OvertimePay       148650 non-null  float64
 4   OtherPay          148650 non-null  float64
 5   Benefits          112491 non-null  float64
 6   TotalPay          148654 non-null  float64
 7   TotalPayBenefits  148654 non-null  float64
 8   Year              148654 non-null  int64
 9   Agency            148654 non-null  object
dtypes: float64(6), int64(1), object(3)
memory usage: 16.5+ MB

**¿Cuál es la nueva información del dataframe?**

In [11]:
salarios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148654 entries, 1 to 148654
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   EmployeeName      148654 non-null  object
 1   JobTitle          148654 non-null  object
 2   BasePay           148045 non-null  float64
 3   OvertimePay       148650 non-null  float64
 4   OtherPay          148650 non-null  float64
 5   Benefits          112491 non-null  float64
 6   TotalPay          148654 non-null  float64
 7   TotalPayBenefits  148654 non-null  float64
 8   Year              148654 non-null  int64
 9   Agency            148654 non-null  object
dtypes: float64(6), int64(1), object(3)
memory usage: 16.5+ MB

- Se puede verificar que al borrar las columnas que no tenian solo *NaN* se disminuye el tamaño del dataframe a: *memory usage: 12.5+ MB*

**Visualizar los primeros 5 registros del DataFrame.**

In [12]:
salarios.head(5)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
Id,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,San Francisco
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,San Francisco
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,San Francisco
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,San Francisco
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,San Francisco

**Visualizar los ultimos 5 registros del DataFrame.**

In [13]:
salarios.tail(5)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
Id,,,,,,,,,,
148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,San Francisco
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,San Francisco
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,San Francisco
148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,San Francisco
148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,San Francisco

**¿Cuántas filas y columnas tiene el dataframe?**

In [15]:
salarios.shape

(148654, 10)

**Visualizar los 10 registros que están a partir del indice 3000**

In [24]:
salarios.iloc[3000:3010]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
Id,,,,,,,,,,
3001,WILLIAM BOYLE,FIREFIGHTER,105934.65,18530.98,16389.60,NaN,140855.23,140855.23,2011,San Francisco
3002,ALAN LIN,ELECTRONIC MAINTENANCE TECHNICIAN,98965.80,41504.40,380.00,NaN,140850.20,140850.20,2011,San Francisco
3003,WILLIAM CONLEY,SERGEANT III (POLICE DEPARTMENT),130457.78,3131.42,7256.39,NaN,140845.59,140845.59,2011,San Francisco
3004,ROBERT MCDONALD,"LIEUTENANT, FIRE DEPARTMENT",123104.99,1833.56,15897.68,NaN,140836.23,140836.23,2011,San Francisco
3005,MICHAEL COSTELLO,POLICE OFFICER III,112401.08,7957.74,20466.93,NaN,140825.75,140825.75,2011,San Francisco
3006,EDNA HO,MANAGER V,140821.37,0.00,0.00,NaN,140821.37,140821.37,2011,San Francisco
3007,RODRIGO CONEL,REGISTERED NURSE,126120.00,3981.78,10714.21,NaN,140815.99,140815.99,2011,San Francisco
3008,VICTOR HURTADO,FIREFIGHTER,105934.67,13112.76,21763.50,NaN,140810.93,140810.93,2011,San Francisco
3009,DONALD LANDRY,TRANSIT POWER LINE WORKER,92861.50,39789.32,8135.86,NaN,140786.68,140786.68,2011,San Francisco
3010,FRANK LEE,"INSPECTOR III, (POLICE DEPARTMENT)",130481.56,725.40,9579.58,NaN,140786.54,140786.54,2011,San Francisco


La columna *Benefits* tiene valores `NaN`, ¿Cuantos NaN tiene la columna *Benefits*? (TIP: Seleccionar la columna y veficar cuantos NaN tiene con `.isna()`. Luego súmalos `.sum()`)

In [37]:
salarios[salarios['Benefits'].isna()]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
Id,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,San Francisco
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,San Francisco
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,San Francisco
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,San Francisco
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,San Francisco
...,...,...,...,...,...,...,...,...,...,...
36159,JOSEPHINE MCCREARY,MANAGER IV,0.00,0.00,0.00,NaN,0.00,0.00,2011,San Francisco
148647,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,San Francisco
148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,San Francisco
148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,San Francisco
148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,San Francisco

Al parecer los valores faltantes en la columna Benefits es por que no se le pagan beneficios entonces:

**Reemplazar los valores *NaN* de la columna *Benefits* por el valor de cero (Usa el parámetro inplace) y mostrar los primeros 10 elementos de la lista**

In [40]:
salarios['Benefits']=0
salarios.head(10)

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
Id,,,,,,,,,,
1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,0,567595.43,567595.43,2011,San Francisco
2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,0,538909.28,538909.28,2011,San Francisco
3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,0,335279.91,335279.91,2011,San Francisco
4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,0,332343.61,332343.61,2011,San Francisco
5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,0,326373.19,326373.19,2011,San Francisco
6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.00,8601.00,189082.74,0,316285.74,316285.74,2011,San Francisco
7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.90,134426.14,0,315981.05,315981.05,2011,San Francisco
8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.00,51322.50,0,307899.46,307899.46,2011,San Francisco
9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,0,303427.55,303427.55,2011,San Francisco
10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.00,0.00,17115.73,0,302377.73,302377.73,2011,San Francisco

**¿Cuál es la nueva información del dataframe?**

In [41]:
salarios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 148654 entries, 1 to 148654
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   EmployeeName      148654 non-null  object
 1   JobTitle          148654 non-null  object
 2   BasePay           148045 non-null  float64
 3   OvertimePay       148650 non-null  float64
 4   OtherPay          148650 non-null  float64
 5   Benefits          148654 non-null  int64
 6   TotalPay          148654 non-null  float64
 7   TotalPayBenefits  148654 non-null  float64
 8   Year              148654 non-null  int64
 9   Agency            148654 non-null  object
dtypes: float64(5), int64(2), object(3)
memory usage: 16.5+ MB

**¿Cuántos valores únicos hay en las columnas categóricas?**

In [55]:
display(salarios.describe(include='all'))

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
count,148654,148654,148045.000000,148650.000000,148650.000000,148654.0,148654.000000,148654.000000,148654.000000,148654
unique,110811,2159,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
top,Kevin Lee,Transit Operator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,San Francisco
freq,13,7036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,148654
mean,NaN,NaN,66325.448840,5066.059886,3648.767297,0.0,74768.321972,93692.554811,2012.522643,NaN
std,NaN,NaN,42764.635495,11454.380559,8056.601866,0.0,50517.005274,62793.533483,1.117538,NaN
min,NaN,NaN,-166.010000,-0.010000,-7058.590000,0.0,-618.130000,-618.130000,2011.000000,NaN
25%,NaN,NaN,33588.200000,0.000000,0.000000,0.0,36168.995000,44065.650000,2012.000000,NaN
50%,NaN,NaN,65007.450000,0.000000,811.270000,0.0,71426.610000,92404.090000,2013.000000,NaN
75%,NaN,NaN,94691.050000,4658.175000,4236.065000,0.0,105839.135000,132876.450000,2014.000000,NaN
max,NaN,NaN,319275.010000,245131.880000,400184.250000,0.0,567595.430000,567595.430000,2014.000000,NaN

- la columna **Agency** solamente tiene un valor unico, entonces no aporta informacion, por lo tanto se puede eliminar

**Elimina la columna *Agency* del dataframe**

In [57]:
del salarios['Agency']

**¿Cuál es el promedio de BasePay ?**

In [65]:
salarios['BasePay'].describe().mean

<bound method Series.mean of count    148045.000000
mean      66325.448840
std       42764.635495
min        -166.010000
25%       33588.200000
50%       65007.450000
75%       94691.050000
max      319275.010000
Name: BasePay, dtype: float64>

**¿Cuál es la cantidad más alta de OvertimePay en el dataset ?**

In [66]:
salarios['OvertimePay'].max()

245131.88

**Realiza una descripción estadística de las columnas numéricas**

**En este dataset las variables `Id` y `Year` representan variables categóricas. Convierte estas columnas a su formato correcto**

**La variable `Year` es categórica ordinal. Detectar cuales son los valores únicos que tiene la columna**

**A partir de la información anterior, convierte la columna `Year` en variable categórica ordinal y visualiza la columna**

**Realiza nuevamente una descripción estadística de las columnas numéricas**

**¿Cuál es el título de trabajo de JOSEPH DRISCOLL? (Nota: Utiliza mayúsculas, de lo contrario, puedes obtener una respuesta que no sea correcta.)**

**¿Cuánto gana JOSEPH DRISCOLL (incluyendo beneficios)?**

**¿Cuál es el nombre de la persona con mejor pago (incluyendo beneficios)?**

**¿Cuál es el nombre de la persona peor paga (incluyendo beneficios)? ¿Notas algo extraño sobre cuánto le pagan?**

**¿Cuántos registros tienen un valor de TotalPayBeneficts menor que cero?**

**¿Cuál es el promedio (mean) BasePay de todos los empleados por año? (Los años van entre (2011-2014))?** (Tip: Usar groupby)

**¿Cuántos títulos de trabajos (JobTitle) únicos existen?**

**¿Cuáles son los 5 trabajos más comunes?**

**¿Cuántos puestos de trabajo Unicos existieron en 2013? (Ejemplo, los títulos de trabajo con solo una ocurrencia en 2013?)**

**¿Cuántas personas tienen la palabra Chief en el título de su trabajo?** Apoyese en los métodos para manipular strings y en el método `.apply()`

**Bono: ¿Existe una correlación entre la longitud del nombre del Título del trabajo y el Salario?**

crea una nueva columna donde se guarde la longitud del titulo del trabajo. tip: usar el método `.apply()`

Utilice el método `.corr()` de Pandas para calcular la correlacion